### ISSUE TITLE
JAN/2017 release

### ISSUE THREAD

**Issue by snmsts** [roswell/roswell#200]
done this month
- [x] fix return code of scripts and build executable differs #207
- [x] fix bug when loading system provided by quicklisp with "/"  #205
- [x] fix? making clisp fails when parallelism is enabled #201
- [x] fix Cannot use ecl/16.1.3 on OSX #199
- [x] fix ci broken (still broken but it comes from quicklisp update)

todo lists for this month.

prioritized
---
- [ ] support installation allegro 10.1 beta (notice it's a bit difficult)
- [ ] better msys2 setup on windows.
- [ ] fix download error on windows when the destination path has white space. #191 

less prioritized
----
- [ ] implement ros get (separate install and get)
- [ ] implement ros update
- [ ] ros install for arbitrary git repo #184
- [ ] fix bug ros build with ecl
- [ ] ros template
- [ ] ros daemon #74 
- [ ] support installing ccl-bin/1.11 for windows (see #165)
- [ ] locale suport #8 
- [ ] documentation. docker example? #162

**Comment by snmsts** [comment]
released.
