### ISSUE TITLE
FEB/2017 release

### ISSUE THREAD

**Issue by snmsts** [roswell/roswell#213]
done this month
---
- [x] support clasp
- [x] 'ros install sbcl/git' to clone from github and compile.
- [x] 'ros emacs take -L option'

prioritized
---
- [ ] support installation allegro 10.1 beta (notice it's a bit difficult)
- [ ] better msys2 setup on windows.
- [ ] fix download error on windows when the destination path has white space. #191 

less prioritized
----
- [ ] implement ros get (separate install and get)
- [ ] implement ros update
- [ ] ros install for arbitrary git repo #184
- [ ] fix bug ros build with ecl
- [ ] ros template
- [ ] ros daemon #74 
- [ ] support installing ccl-bin/1.11 for windows (see #165)
- [ ] locale suport #8 
- [ ] documentation. docker example? #162

**Comment by guicho271828** [comment]
um, dont you consider using milestone?

**Comment by snmsts** [comment]
um.I'll try from march.
